outputPath = 'build'

inputPath = 'src/docs'

inputFiles = [
        /** inputFiles **/
]

// folders in which asciidoc will find images.
// these will be copied as resources to ./images
// folders are relative to inputPath
imageDirs = [
    /** imageDirs **/
]

// whether the build should fail when detecting broken image references
// if this config is set to true all images will be embedded
failOnMissingImages = true

// these are directories (dirs) and files which Gradle monitors for a change
// in order to decide if the docs have to be re-build
taskInputsDirs = [
                    "${inputPath}",
              ]

taskInputsFiles = []

//******************************************************************************

// Configuration for microsite: generateSite + previewSite

microsite = [:]

microsite.with {

    // is your microsite deployed with a context path?
    contextPath = '/opencode-semantic-anchors/'

    //project theme
    //site folder relative to the docs folder
    //see 'copyTheme' for more details
    siteFolder = '../site'

    // the title of the microsite, displayed in the upper left corner
    title = 'opencode-semantic-anchors'

    // contact eMail
    footerMail = 'mailto:jens@grote.org'

    // Github Repository
    footerGithub = 'https://github.com/JensGrote/opencode-semantic-anchors'

    // Footer Text
    footerText = '<small class="text-white">built with <a href="https://doctoolchain.org">docToolchain</a> and <a href="https://jbake.org">jBake</a></small>'

    // the url to create an issue in github
    issueUrl = 'https://github.com/JensGrote/opencode-semantic-anchors/issues/new'

    // the base url for code files in github
    branch = System.getenv("DTC_PROJECT_BRANCH")?:'main'
    gitRepoUrl = 'https://github.com/JensGrote/opencode-semantic-anchors'

    // the location of the landing page
    landingPage = 'landingpage.gsp'

    // the menu of the microsite. A map of [code:'title'] entries to specify the order and title of the entries.
    // the codes are autogenerated from the folder names or :jbake-menu: attribute entries from the .adoc file headers
    // set a title to '-' in order to remove this menu entry.
    menu = [
        en: 'English',
        de: 'Deutsch'
    ]

    // if you prefer another convention regarding the automatic generation
    // of jBake headers, you can configure a script to modify them here
    customConvention = """
        if (file.canonicalPath.contains('/09-adrs/') && file.name.startsWith('ADR-')) {
            headers.order = 100
            headers.status = 'published'
        }
    """.stripIndent()

    // define a custom search html
    /**
    search = """        <form action="${content.rootpath}search.html">
        <input aria-label="Search this site…" autocomplete="off" class="form-control td-search-input"
               placeholder="🔍 Search this site…" type="search" name="q">
        </form>
    """
    **/
}
